require('settings')
require('color-schemes-config.nightfox')
require('packer-config')
require('nvim-tree-config')
require('nvim-web-icons-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
